import { useAuth } from "@/_core/hooks/useAuth";
import { PlatformHeader } from "@/components/PlatformHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileImage, Gavel, Loader2, ShieldAlert, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

type ImportSource = "fipi" | "partner";

export default function AdminIntake() {
  const { user, loading } = useAuth();
  const isAdmin = user?.role === "admin";
  const options = trpc.school.admin.options.useQuery(undefined, { enabled: isAdmin });
  const imports = trpc.school.admin.importCases.useQuery(undefined, { enabled: isAdmin });
  const media = trpc.school.admin.externalMediaQueue.useQuery(undefined, { enabled: isAdmin });
  const [sourceKind, setSourceKind] = useState<ImportSource>("fipi");
  const [kimNumber, setKimNumber] = useState("");
  const [sourceTitle, setSourceTitle] = useState("");
  const [sourceUrl, setSourceUrl] = useState("");
  const [sourceRecordId, setSourceRecordId] = useState("");
  const [proposedTitle, setProposedTitle] = useState("");
  const [sourceSummary, setSourceSummary] = useState("");
  const [plannedAdaptation, setPlannedAdaptation] = useState("");
  const [decisionNotes, setDecisionNotes] = useState<Record<number, string>>({});
  const [convertCaseId, setConvertCaseId] = useState<number | null>(null);
  const [draft, setDraft] = useState({ slug: "", title: "", topicSlug: "", statementMarkdown: "", solutionMarkdown: "", difficulty: "standard" as "basic" | "standard" | "advanced", answerKind: "short_integer" as "short_integer" | "short_decimal" | "short_text" | "manual", correctAnswer: "" });
  const refresh = (message: string) => { imports.refetch(); media.refetch(); toast.success(message); };
  const submit = trpc.school.admin.submitImportCase.useMutation({ onSuccess: () => refresh("Карточка отправлена на правовую проверку."), onError: error => toast.error(error.message) });
  const clear = trpc.school.admin.clearImportCase.useMutation({ onSuccess: () => refresh("Правовое основание зафиксировано."), onError: error => toast.error(error.message) });
  const reject = trpc.school.admin.rejectImportCase.useMutation({ onSuccess: () => refresh("Импорт отклонён с обоснованием."), onError: error => toast.error(error.message) });
  const convert = trpc.school.admin.convertImportCase.useMutation({ onSuccess: result => { refresh("Создан редакторский черновик."); setConvertCaseId(null); setDraft({ slug: "", title: "", topicSlug: "", statementMarkdown: "", solutionMarkdown: "", difficulty: "standard", answerKind: "short_integer", correctAnswer: "" }); toast.message(`Черновик #${result.taskId} доступен в редакторе заданий.`); }, onError: error => toast.error(error.message) });
  const moderate = trpc.school.admin.moderateExternalMedia.useMutation({ onSuccess: result => refresh(result.reviewStatus === "approved" ? "Изображение утверждено для публичного показа." : "Изображение отклонено."), onError: error => toast.error(error.message) });
  const clearedCases = useMemo(() => imports.data?.filter(item => item.status === "cleared") ?? [], [imports.data]);

  if (loading) return <div className="theme-page grid min-h-screen place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#ff5b14]" /></div>;
  if (!isAdmin) return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-16"><h1 className="text-3xl font-bold">Очереди импорта доступны только администратору.</h1></main></div>;

  return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-10 sm:py-14">
    <section className="theme-surface rounded-[28px] border p-6 sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#ff7a35]">Контентный слой / права и медиа</p><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-4xl font-bold tracking-[-.055em] sm:text-5xl">Контроль импорта</h1><p className="theme-muted mt-3 max-w-3xl text-sm leading-6">Внешний материал не может стать задачей до решения о правовом основании. Внешнее изображение также не появится публично до независимой модерации.</p></div><Link href="/admin/tasks/control"><Button variant="outline" className="rounded-xl border-white/12 bg-white/4 text-[#f5f0e9]">Вернуться к задачам</Button></Link></div></section>

    <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="space-y-6"><section className="theme-surface rounded-2xl border p-5"><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-[#ff7a35]" /><h2 className="text-xl font-bold">Новая карточка ручного импорта</h2></div><p className="theme-muted mt-2 text-sm">Формулировка внешней задачи не загружается сюда: сначала регистрируются источник, краткая справка и план авторской адаптации.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><Label>Классификация источника</Label><select value={sourceKind} onChange={event => setSourceKind(event.target.value as ImportSource)} className="mt-2 h-10 w-full rounded-lg px-3"><option value="fipi">ФИПИ / официальный источник</option><option value="partner">Партнёрский или иной источник</option></select></div><div><Label>Номер КИМ</Label><select value={kimNumber} onChange={event => setKimNumber(event.target.value)} className="mt-2 h-10 w-full rounded-lg px-3"><option value="">Выберите номер</option>{options.data?.taskTypes.map(item => <option key={item.kimNumber} value={item.kimNumber}>№ {item.kimNumber} · {item.title}</option>)}</select></div><div><Label>Название источника</Label><Input value={sourceTitle} onChange={event => setSourceTitle(event.target.value)} className="mt-2" placeholder="Например, Открытый банк…" /></div><div><Label>URL первоисточника</Label><Input value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} className="mt-2" placeholder="https://…" /></div><div><Label>ID записи в источнике</Label><Input value={sourceRecordId} onChange={event => setSourceRecordId(event.target.value)} className="mt-2" placeholder="Необязательно" /></div><div><Label>Рабочее название черновика</Label><Input value={proposedTitle} onChange={event => setProposedTitle(event.target.value)} className="mt-2" placeholder="Как назвать адаптированную задачу" /></div></div><div className="mt-4 grid gap-4"><div><Label>Краткая справка об источнике</Label><Textarea value={sourceSummary} onChange={event => setSourceSummary(event.target.value)} className="mt-2 min-h-24" placeholder="Что найдено, где расположено и зачем рассматривается…" /></div><div><Label>План авторской адаптации</Label><Textarea value={plannedAdaptation} onChange={event => setPlannedAdaptation(event.target.value)} className="mt-2 min-h-24" placeholder="Какая новая формулировка, данные, схема или методика будут созданы редакцией…" /></div></div><Button className="mt-5 rounded-xl bg-[#ff5b14] font-bold text-[#101014] hover:bg-[#ff7a35]" disabled={submit.isPending} onClick={() => submit.mutate({ kimNumber, sourceKind, sourceTitle, sourceUrl, sourceRecordId: sourceRecordId || undefined, proposedTitle, sourceSummary, plannedAdaptation })}>{submit.isPending ? "Отправляем…" : "Передать на правовую проверку"}</Button></section>

      <section className="theme-surface rounded-2xl border p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Gavel className="h-5 w-5 text-[#ff7a35]" /><h2 className="text-xl font-bold">Очередь правовой проверки</h2></div><Badge>{imports.data?.length ?? 0}</Badge></div><div className="mt-4 space-y-3">{imports.data?.length ? imports.data.map(item => <article key={item.id} className="rounded-xl border border-white/8 bg-white/3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><Badge className="border-0 bg-[#ff5b14]/14 text-[#ff8b4b] hover:bg-[#ff5b14]/14">КИМ № {item.kimNumber}</Badge><Badge variant="outline" className="border-white/12 text-[#aaa7ae]">{item.status}</Badge></div><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-[#ff8b4b]">Открыть источник</a></div><h3 className="mt-3 font-bold">{item.proposedTitle}</h3><p className="theme-muted mt-1 text-xs">{item.sourceTitle} · {item.taskTypeTitle}</p><p className="theme-muted mt-3 text-sm">{item.plannedAdaptation}</p>{item.status === "rights_review" ? <div className="mt-4"><Textarea value={decisionNotes[item.id] ?? ""} onChange={event => setDecisionNotes(prev => ({ ...prev, [item.id]: event.target.value }))} className="min-h-20" placeholder="Основание решения и обязательный комментарий…" /><div className="mt-2 flex flex-wrap gap-2"><Button size="sm" onClick={() => clear.mutate({ importCaseId: item.id, note: decisionNotes[item.id] ?? "", rightsBasis: decisionNotes[item.id] ?? "" })} className="bg-emerald-500/20 text-emerald-200 hover:bg-emerald-500/30"><CheckCircle2 className="mr-1 h-4 w-4" />Одобрить основание</Button><Button size="sm" variant="outline" onClick={() => reject.mutate({ importCaseId: item.id, note: decisionNotes[item.id] ?? "" })} className="border-rose-400/30 text-rose-200 hover:bg-rose-400/10"><XCircle className="mr-1 h-4 w-4" />Отклонить</Button></div></div> : null}{item.status === "cleared" ? <Button size="sm" className="mt-4 bg-[#ff5b14] text-[#101014] hover:bg-[#ff7a35]" onClick={() => { setConvertCaseId(item.id); setDraft(prev => ({ ...prev, title: item.proposedTitle })); }}>Создать редакторский черновик</Button> : null}{item.legalReviewNote ? <p className="mt-3 rounded-lg bg-white/4 p-2 text-xs text-[#c7c3ca]">Решение: {item.legalReviewNote}</p> : null}</article>) : <p className="theme-muted text-sm">Карточек в очереди пока нет.</p>}</div></section>

      {convertCaseId ? <section className="theme-surface rounded-2xl border p-5"><h2 className="text-xl font-bold">Конвертация в черновик</h2><p className="theme-muted mt-2 text-sm">Создаётся непубличная задача с зарегистрированным источником; далее содержание проходит обычный редакторский цикл.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input value={draft.slug} onChange={event => setDraft(prev => ({ ...prev, slug: event.target.value }))} placeholder="slug-na-latinice" /><Input value={draft.title} onChange={event => setDraft(prev => ({ ...prev, title: event.target.value }))} placeholder="Название" /><select value={draft.topicSlug} onChange={event => setDraft(prev => ({ ...prev, topicSlug: event.target.value }))} className="h-10 rounded-lg px-3"><option value="">Тема</option>{options.data?.topics.map(item => <option key={item.slug} value={item.slug}>{item.title}</option>)}</select><select value={draft.answerKind} onChange={event => setDraft(prev => ({ ...prev, answerKind: event.target.value as typeof draft.answerKind }))} className="h-10 rounded-lg px-3"><option value="short_integer">Краткий целый ответ</option><option value="short_decimal">Краткий десятичный ответ</option><option value="short_text">Краткий текстовый ответ</option><option value="manual">Развёрнутый ответ</option></select></div><Textarea value={draft.statementMarkdown} onChange={event => setDraft(prev => ({ ...prev, statementMarkdown: event.target.value }))} className="mt-4 min-h-24" placeholder="Редакторская формулировка" /><Textarea value={draft.solutionMarkdown} onChange={event => setDraft(prev => ({ ...prev, solutionMarkdown: event.target.value }))} className="mt-3 min-h-24" placeholder="Редакторское решение" />{draft.answerKind !== "manual" ? <Input value={draft.correctAnswer} onChange={event => setDraft(prev => ({ ...prev, correctAnswer: event.target.value }))} className="mt-3" placeholder="Верный ответ" /> : null}<div className="mt-4 flex gap-2"><Button onClick={() => convert.mutate({ importCaseId: convertCaseId, ...draft, correctAnswer: draft.correctAnswer || undefined })} className="bg-[#ff5b14] text-[#101014] hover:bg-[#ff7a35]">Создать черновик</Button><Button variant="ghost" onClick={() => setConvertCaseId(null)}>Отмена</Button></div></section> : null}</section>

      <aside><section className="theme-surface rounded-2xl border p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><FileImage className="h-5 w-5 text-[#ff7a35]" /><h2 className="text-xl font-bold">Внешние изображения</h2></div><Badge>{media.data?.length ?? 0}</Badge></div><p className="theme-muted mt-2 text-sm">Только изображения, ожидающие независимого решения модератора.</p><div className="mt-4 space-y-4">{media.data?.length ? media.data.map(item => <article key={item.id} className="rounded-xl border border-white/8 bg-white/3 p-3"><img src={item.assetUrl ?? ""} alt={item.altText} className="h-32 w-full rounded-lg object-cover" /><p className="mt-3 text-sm font-bold">{item.taskTitle}</p><p className="theme-muted mt-1 text-xs">КИМ № {item.kimNumber} · {item.placement === "statement" ? "к условию" : "к решению"}</p><a href={item.sourceUrl ?? "#"} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-[#ff8b4b]">Проверить источник</a><Textarea value={decisionNotes[item.id] ?? ""} onChange={event => setDecisionNotes(prev => ({ ...prev, [item.id]: event.target.value }))} className="mt-3 min-h-20" placeholder="Мотив решения…" /><div className="mt-2 flex gap-2"><Button size="sm" onClick={() => moderate.mutate({ visualId: item.id, decision: "approved", note: decisionNotes[item.id] ?? "" })} className="bg-emerald-500/20 text-emerald-200 hover:bg-emerald-500/30">Утвердить</Button><Button size="sm" variant="outline" onClick={() => moderate.mutate({ visualId: item.id, decision: "rejected", note: decisionNotes[item.id] ?? "" })} className="border-rose-400/30 text-rose-200 hover:bg-rose-400/10">Отклонить</Button></div></article>) : <p className="theme-muted text-sm">Новых внешних изображений нет.</p>}</div></section>{clearedCases.length ? <p className="theme-muted mt-4 text-xs">Одобрено к конвертации: {clearedCases.length}.</p> : null}</aside></div>
  </main></div>;
}
