import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { PlatformHeader } from "@/components/PlatformHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, Clock3, Loader2, Sparkles, XCircle } from "lucide-react";
import { Link } from "wouter";

export default function PracticeCenter() {
  const { isAuthenticated, loading } = useAuth();
  const practice = trpc.learning.practiceSet.useQuery(undefined, { enabled: isAuthenticated });
  const history = trpc.learning.attemptHistory.useQuery(undefined, { enabled: isAuthenticated });

  if (!loading && !isAuthenticated) return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-16"><section className="mx-auto max-w-2xl rounded-3xl bg-[#0d2945] p-9 text-white"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#e9c46a]">Личная практика</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-0.055em]">Собирайте свой набор задач.</h1><p className="mt-4 leading-7 text-slate-300">Войдите, чтобы превратить сохранённые задания в короткую практику и видеть историю ответов.</p><Button onClick={startLogin} className="mt-7 rounded-lg bg-[#e9c46a] font-extrabold text-[#0d2945]">Войти в тренажёр</Button></section></main></div>;
  if (loading || practice.isLoading || history.isLoading) return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container grid min-h-72 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#2c668f]" /></main></div>;

  return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-9 sm:py-12"><div className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#2c668f]">Личная практика</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-0.055em] text-slate-950">Следующие задачи для вас</h1><p className="mt-4 text-base leading-7 text-slate-600">{practice.data?.source === "saved" ? "Подборка собрана из сохранённых вами задач." : "Стартовая подборка поможет начать. Сохраняйте полезные задачи, и она станет персональной."}</p></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-[#b88318]" /><h2 className="text-lg font-extrabold text-slate-950">Подборка на сейчас</h2></div><div className="mt-5 space-y-3">{practice.data?.tasks.map((task, index) => <Link key={task.id} href={`/bank/${task.slug}`} className="group flex items-center justify-between gap-4 rounded-xl bg-[#f7f9fa] p-4 transition hover:bg-[#edf5fa]"><div><p className="text-xs font-extrabold text-[#2c668f]">0{index + 1} · КИМ {task.kimNumber}</p><p className="mt-1 font-extrabold text-slate-900">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.topicTitle}</p></div><ArrowRight className="h-4 w-4 text-[#245d87] transition-transform group-hover:translate-x-1" /></Link>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-[#2c668f]" /><h2 className="text-lg font-extrabold text-slate-950">История попыток</h2></div><div className="mt-5 space-y-3">{history.data?.length ? history.data.map(item => <Link key={item.id} href={`/bank/${item.taskSlug}`} className="block rounded-xl border border-slate-100 p-3 transition hover:border-[#c8ddea] hover:bg-[#fbfdff]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold text-slate-900">{item.taskTitle}</p><p className="mt-1 text-xs text-slate-500">КИМ {item.kimNumber} · {item.topicTitle} · {new Date(item.submittedAt).toLocaleString("ru-RU")}</p></div>{item.checkStatus === "correct" ? <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" /> : <XCircle className="h-5 w-5 shrink-0 text-rose-500" />}</div><div className="mt-2 flex gap-2"><Badge variant="outline">Ответ: {item.rawAnswer}</Badge><Badge className={item.checkStatus === "correct" ? "bg-emerald-100 text-emerald-700 hover:bg-emerald-100" : "bg-rose-100 text-rose-700 hover:bg-rose-100"}>{item.checkStatus === "correct" ? "Верно" : item.checkStatus === "incorrect" ? "Неверно" : "На проверке"}</Badge></div></Link>) : <p className="rounded-xl bg-[#f6fafc] p-4 text-sm leading-6 text-slate-600">Здесь появятся ответы после первой попытки. Откройте любую задачу и проверьте себя.</p>}</div></section></div></main></div>;
}
