import { useAuth } from "@/_core/hooks/useAuth";
import { PlatformHeader } from "@/components/PlatformHeader";
import { CabinetSidebar, MobileCabinetDrawer } from "@/components/CabinetSidebar";
import { Button } from "@/components/ui/button";
import { useTheme } from "@/contexts/ThemeContext";
import { Moon, Sun, UserRound } from "lucide-react";

export default function SettingsPage() {
  const { user, isAuthenticated, logout } = useAuth(); const { theme, toggleTheme } = useTheme();
  if (!isAuthenticated) return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-16"><p className="theme-muted">Войдите, чтобы открыть настройки.</p></main></div>;
  return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container grid gap-6 py-8 sm:py-12 lg:grid-cols-[220px_minmax(0,1fr)]"><CabinetSidebar /><div className="lg:hidden"><MobileCabinetDrawer /></div><section className="theme-surface max-w-3xl rounded-2xl border p-6 sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#ff7a35]">Отдельный раздел</p><h1 className="mt-3 text-3xl font-bold tracking-[-.05em]">Настройки</h1><div className="mt-7 space-y-3"><article className="flex flex-col gap-4 rounded-xl border border-white/8 bg-white/[.025] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><UserRound className="mt-0.5 h-5 w-5 text-[#ff7a35]" /><div><p className="font-bold">Аккаунт</p><p className="theme-muted mt-1 text-sm">{user?.name || "Пользователь"}{user?.email ? ` · ${user.email}` : ""}</p></div></div></article><article className="flex flex-col gap-4 rounded-xl border border-white/8 bg-white/[.025] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Оформление</p><p className="theme-muted mt-1 text-sm">Текущая тема: {theme === "dark" ? "тёмная" : "светлая"}.</p></div><Button variant="outline" onClick={toggleTheme} className="border-white/12">{theme === "dark" ? <Sun className="mr-2 h-4 w-4" /> : <Moon className="mr-2 h-4 w-4" />}{theme === "dark" ? "Светлая" : "Тёмная"}</Button></article><article className="flex flex-col gap-4 rounded-xl border border-white/8 bg-white/[.025] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Сеанс</p><p className="theme-muted mt-1 text-sm">Выход не затрагивает учебный прогресс и редакционные записи.</p></div><Button variant="outline" onClick={logout} className="border-white/12 text-[#ff8b4b]">Выйти</Button></article></div></section></main></div>;
}
