import { useAuth } from "@/_core/hooks/useAuth";
import { ContentOrigin } from "@/components/ContentOrigin";
import { PlatformHeader } from "@/components/PlatformHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { TaskVisuals } from "@/components/TaskVisuals";
import { MathMarkdown } from "@/components/MathMarkdown";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Bookmark, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Lightbulb, ListChecks, Loader2, LockKeyhole, XCircle } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";

export default function TaskDetail() {
  const [, params] = useRoute("/bank/:slug");
  const slug = params?.slug ?? "";
  const { isAuthenticated } = useAuth();
  const task = trpc.publicBank.getTask.useQuery({ slug }, { enabled: Boolean(slug) });
  const guestCheck = trpc.publicBank.checkAnswer.useMutation();
  const learningCheck = trpc.learning.submitAttempt.useMutation();
  const saveTask = trpc.learning.saveTask.useMutation();
  const [answer, setAnswer] = useState("");
  const [showSolution, setShowSolution] = useState(false);
  const [revealedHints, setRevealedHints] = useState(0);
  const [revealedSteps, setRevealedSteps] = useState(0);
  const result = learningCheck.data ?? guestCheck.data;
  const submit = () => { if (!task.data || !answer.trim()) return; if (isAuthenticated) learningCheck.mutate({ taskId: task.data.id, rawAnswer: answer }); else guestCheck.mutate({ taskId: task.data.id, rawAnswer: answer }); };
  const openSolution = () => { const next = !showSolution; setShowSolution(next); if (next) setRevealedSteps(0); };

  if (task.isLoading) return <div className="theme-page grid min-h-screen place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#ff5b14]" /></div>;
  if (!task.data) return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-20"><p>Задание не найдено.</p></main></div>;
  const allStepsRevealed = revealedSteps >= task.data.solutionSteps.length;

  return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-9 sm:py-12"><Link href="/bank" className="inline-flex items-center gap-1 text-sm font-bold text-[#ff7a35] hover:text-[#ff9a61]"><ChevronLeft className="h-4 w-4" />Вернуться к банку</Link><div className="mt-7 grid gap-7 lg:grid-cols-[minmax(0,1fr)_310px]">
    <article className="theme-surface overflow-hidden rounded-[28px] border shadow-[0_24px_70px_rgba(0,0,0,.3)]"><div className="border-b border-white/9 bg-[linear-gradient(110deg,rgba(255,91,20,.14),transparent_42%)] p-6 sm:p-9"><div className="flex flex-wrap items-center gap-2"><Badge className="border-0 bg-[#ff5b14] text-[#101014] hover:bg-[#ff5b14]">КИМ {task.data.kimNumber}</Badge><Badge variant="outline" className="border-white/14 text-[#aaa7ae]">Банк · {task.data.catalogNumber}</Badge><Badge variant="outline" className="border-white/14 text-[#aaa7ae]">Часть {task.data.part === "part1" ? "1" : "2"}</Badge><Badge variant="outline" className="border-white/14 text-[#aaa7ae]">{task.data.topicTitle}</Badge></div><div className="mt-4"><ContentOrigin kind={task.data.sourceKind === "fipi" ? "external_reference" : task.data.sourceKind === "partner" ? "licensed" : "author"} title={task.data.sourceTitle || "Источник требует проверки"} url={task.data.sourceUrl} /></div><p className="mt-7 text-[10px] font-extrabold uppercase tracking-[.17em] text-[#7e7b82]">Задание / {task.data.taskType}</p><h1 className="mt-3 max-w-3xl text-3xl font-bold tracking-[-.055em] sm:text-4xl">{task.data.title}</h1><MathMarkdown className="mt-8 max-w-3xl text-lg leading-8 text-[#e2ddd6]">{task.data.statementMarkdown}</MathMarkdown><TaskVisuals visuals={task.data.visuals} placement="statement" /></div>
      {task.data.part === "part1" ? <section className="m-5 rounded-2xl border border-[#ff5b14]/30 bg-[#ff5b14]/8 p-5 sm:m-7 sm:p-6"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#ff5b14] text-[#101014]"><CircleHelp className="h-4 w-4" /></span><p className="text-sm font-extrabold">Введите краткий ответ</p></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Input value={answer} onChange={event => setAnswer(event.target.value)} onKeyDown={event => event.key === "Enter" && submit()} placeholder="Например, 12 или 0,6" className="h-12 rounded-xl text-base" /><Button onClick={submit} disabled={!answer.trim() || guestCheck.isPending || learningCheck.isPending} className="h-12 rounded-xl bg-[#ff5b14] px-6 font-extrabold text-[#101014] hover:bg-[#ff7a35]">Проверить</Button></div>{result ? <div className={`mt-4 flex gap-3 rounded-xl border p-4 text-sm ${result.checkStatus === "correct" ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-100" : "border-[#ff5b14]/35 bg-[#ff5b14]/10 text-[#ffe0d0]"}`}>{result.checkStatus === "correct" ? <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" /> : <XCircle className="h-5 w-5 shrink-0 text-[#ff7a35]" />}<div><p className="font-extrabold">{result.checkStatus === "correct" ? "Верный ответ" : "Проверьте ещё раз"}</p><p className="mt-1 leading-5 opacity-85">{result.feedback}</p>{!isAuthenticated ? <p className="mt-2 flex items-center gap-1 text-xs font-bold"><LockKeyhole className="h-3.5 w-3.5" />Войдите, чтобы результат попал в прогресс.</p> : null}</div></div> : null}</section> : <section className="m-5 rounded-2xl border border-amber-400/25 bg-amber-300/10 p-5 text-sm leading-6 text-amber-100 sm:m-7"><p className="font-extrabold">Часть 2: развёрнутое решение</p><p className="mt-2">Откройте пошаговый разбор ниже: в нём показан ход решения, а когда это нужно — добавлены фотографии и схемы.</p></section>}
      {task.data.hints.length ? <section className="mx-5 mb-5 rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 sm:mx-7"><div className="flex items-center gap-2"><Lightbulb className="h-4 w-4 text-amber-300" /><p className="text-sm font-extrabold">Подсказки — без ответа</p></div><p className="mt-2 text-sm leading-6 text-[#bdb8b1]">Открывайте по одной, если застряли: так сохраняется самостоятельность решения.</p>{task.data.hints.slice(0, revealedHints).map((hint, index) => <div key={hint.id} className="mt-3 rounded-xl border border-amber-200/10 bg-black/10 p-4"><p className="text-xs font-extrabold text-amber-300">{index + 1}. {hint.title}</p><p className="mt-2 whitespace-pre-line text-sm leading-6 text-[#ded8d0]">{hint.bodyMarkdown}</p></div>)}{revealedHints < task.data.hints.length ? <Button variant="outline" onClick={() => setRevealedHints(value => value + 1)} className="mt-4 gap-2 rounded-xl border-amber-300/30 bg-amber-300/5 text-amber-100 hover:bg-amber-300/12 hover:text-amber-50"><Lightbulb className="h-4 w-4" />Показать подсказку {revealedHints + 1} из {task.data.hints.length}</Button> : null}</section> : null}
      <div className="flex flex-wrap gap-3 px-5 pb-7 sm:px-7"><Button variant="outline" onClick={openSolution} className="rounded-xl border-white/15 bg-white/4 font-extrabold text-white hover:bg-white/10 hover:text-white">{showSolution ? "Скрыть разбор" : task.data.solutionSteps.length ? "Открыть пошаговый разбор" : "Открыть разбор"}</Button>{isAuthenticated ? <Button variant="ghost" onClick={() => saveTask.mutate({ taskId: task.data.id })} className="gap-2 rounded-xl text-[#ff7a35] hover:bg-[#ff5b14]/10 hover:text-[#ff9a61]"><Bookmark className="h-4 w-4" />Сохранить</Button> : null}</div>
      {showSolution ? <section className="border-t border-white/9 px-5 py-7 sm:px-7"><div className="flex items-center gap-2"><ListChecks className="h-4 w-4 text-[#ff7a35]" /><p className="text-[10px] font-extrabold uppercase tracking-[.17em] text-[#ff7a35]">Пошаговый разбор</p></div>{task.data.solutionSteps.length ? <><p className="mt-3 text-sm leading-6 text-[#aaa7ae]">Раскрывайте следующий шаг только после собственной попытки.</p><div className="mt-4 space-y-3">{task.data.solutionSteps.slice(0, revealedSteps).map((step, index) => <div key={step.id} className="rounded-2xl border border-white/9 bg-white/3 p-4"><p className="text-sm font-extrabold text-[#ff9a61]">{index + 1}. {step.title}</p><p className="mt-2 whitespace-pre-line text-sm leading-7 text-[#d8d3cc]">{step.bodyMarkdown}</p></div>)}</div>{revealedSteps < task.data.solutionSteps.length ? <Button variant="outline" onClick={() => setRevealedSteps(value => value + 1)} className="mt-4 gap-2 rounded-xl border-[#ff5b14]/35 bg-[#ff5b14]/8 text-[#ffb187] hover:bg-[#ff5b14]/16 hover:text-[#ffd1bb]">Показать шаг {revealedSteps + 1} из {task.data.solutionSteps.length}<ChevronRight className="h-4 w-4" /></Button> : <p className="mt-5 text-sm font-bold text-emerald-300">Разбор завершён — сравните его со своим решением.</p>}</> : <p className="mt-4 whitespace-pre-line text-base leading-8 text-[#d8d3cc]">{task.data.solutionMarkdown}</p>} {allStepsRevealed ? <TaskVisuals visuals={task.data.visuals} placement="solution" /> : null}</section> : null}
    </article>
    <aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><section className="theme-surface rounded-2xl border p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#ff7a35]">Следующий шаг</p><p className="mt-3 text-sm font-bold text-[#f5f0e9]">Связано с теорией</p><div className="mt-3 space-y-2">{task.data.relatedTheory.map(item => <Link key={item.slug} href="/theory" className="group block rounded-xl border border-white/8 bg-[#101012] p-3 transition hover:border-[#ff5b14]/45"><p className="flex items-center justify-between gap-3 font-extrabold text-[#e9e4de]">{item.title}<ArrowUpRight className="h-4 w-4 shrink-0 text-[#ff5b14]" /></p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#929097]">{item.lead}</p></Link>)}</div></section><section className="theme-surface rounded-2xl border p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[#77747b]">Параметры</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-3"><dt className="text-[#8e8b91]">Тип</dt><dd className="text-right font-bold text-[#e6e1da]">{task.data.taskType}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#8e8b91]">Год ОГЭ</dt><dd className="font-bold text-[#e6e1da]">{task.data.sourceExamYear ?? "Требует проверки"}</dd></div></dl></section></aside>
  </div></main></div>;
}
