import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { PlatformHeader } from "@/components/PlatformHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Check, ClipboardPlus, Copy, Loader2, MailPlus, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function TutorWorkspace() {
  const { isAuthenticated, loading } = useAuth();
  const profile = trpc.profile.me.useQuery(undefined, { enabled: isAuthenticated });
  const students = trpc.school.tutor.students.useQuery(undefined, { enabled: profile.data?.learningRole === "tutor" });
  const homework = trpc.school.tutor.homework.useQuery(undefined, { enabled: profile.data?.learningRole === "tutor" });
  const catalog = trpc.publicBank.listTasks.useQuery({});
  const createInvite = trpc.school.tutor.createInvite.useMutation({ onSuccess: () => { students.refetch(); toast.success("Приглашение создано"); } });
  const createHomework = trpc.school.tutor.createHomework.useMutation({ onSuccess: () => { homework.refetch(); toast.success("Домашняя работа назначена"); } });
  const [email, setEmail] = useState("");
  const [studentId, setStudentId] = useState<number | null>(null);
  const [title, setTitle] = useState("Практика по ОГЭ");
  const [dueDate, setDueDate] = useState("");
  const [selectedTasks, setSelectedTasks] = useState<number[]>([]);
  const activeStudents = useMemo(() => students.data?.filter(student => student.status === "active") ?? [], [students.data]);

  const toggleTask = (taskId: number) => setSelectedTasks(current => current.includes(taskId) ? current.filter(id => id !== taskId) : [...current, taskId]);
  const copyInvite = async (code: string) => { await navigator.clipboard.writeText(code); toast.success("Код приглашения скопирован"); };

  if (!loading && !isAuthenticated) return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-16"><section className="mx-auto max-w-xl rounded-3xl bg-[#0d2945] p-9 text-white"><h1 className="text-3xl font-extrabold">Кабинет репетитора</h1><p className="mt-3 leading-6 text-slate-300">Войдите, чтобы приглашать учеников и назначать задания из банка.</p><Button onClick={startLogin} className="mt-6 bg-[#e9c46a] font-extrabold text-[#0d2945]">Войти</Button></section></main></div>;
  if (profile.isLoading) return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container grid min-h-72 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-[#2c668f]" /></main></div>;
  if (isAuthenticated && profile.data?.learningRole === "unselected") return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-16"><section className="mx-auto max-w-2xl rounded-3xl border border-[#d9e4ed] bg-white p-8 shadow-sm"><h1 className="text-3xl font-extrabold tracking-[-0.05em] text-slate-950">Сначала выберите роль</h1><p className="mt-3 max-w-lg leading-7 text-slate-600">Кабинет репетитора откроется после выбора роли при первом входе.</p><Link href="/workspace"><Button className="mt-6 rounded-lg bg-[#0d2945] font-extrabold">Перейти к выбору роли</Button></Link></section></main></div>;
  if (profile.data?.learningRole !== "tutor") return <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-16"><section className="rounded-3xl border border-amber-200 bg-amber-50 p-8 text-amber-950"><h1 className="text-2xl font-extrabold">Кабинет доступен репетитору</h1><p className="mt-3 leading-6">Ваша роль сейчас — ученик. Её может изменить администратор платформы.</p></section></main></div>;

  return (
    <div className="min-h-screen bg-[#f7f8f5]"><PlatformHeader /><main className="container py-9 sm:py-12"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#2c668f]">Рабочее пространство</p><h1 className="mt-2 text-4xl font-extrabold tracking-[-0.055em] text-slate-950">Кабинет репетитора</h1><p className="mt-3 text-sm leading-6 text-slate-600">Подключайте учеников и выдавайте им точные подборки из открытого банка.</p></div><div className="rounded-xl bg-[#e9f2f8] px-4 py-3 text-sm font-bold text-[#245d87]"><UsersRound className="mr-2 inline h-4 w-4" /> {activeStudents.length} активных учеников</div></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.4fr]"><section className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><MailPlus className="h-5 w-5 text-[#2c668f]" /><h2 className="text-lg font-extrabold text-slate-950">Пригласить ученика</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">Ученик должен сначала войти и выбрать роль «Ученик».</p><form className="mt-5 space-y-3" onSubmit={event => { event.preventDefault(); createInvite.mutate({ studentEmail: email }); }}><Label htmlFor="student-email">Почта ученика</Label><Input id="student-email" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="student@example.com" required /><Button type="submit" disabled={createInvite.isPending} className="w-full rounded-lg bg-[#0d2945] font-bold">Создать код приглашения</Button></form></div>
        <div className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold text-slate-950">Ученики</h2><div className="mt-4 space-y-3">{students.data?.length ? students.data.map(student => <div key={student.linkId} className="rounded-xl bg-[#f7f9fa] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-extrabold text-slate-900">{student.studentName || student.studentEmail}</p><p className="mt-1 text-xs text-slate-500">{student.status === "active" ? "Подключён" : "Ожидает активации"}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold uppercase tracking-wide ${student.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>{student.status === "active" ? "Активен" : "Ожидает"}</span></div>{student.status === "pending" ? <button type="button" onClick={() => copyInvite(student.inviteCode)} className="mt-3 flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs font-extrabold text-[#245d87] shadow-sm">Код {student.inviteCode} <Copy className="h-3.5 w-3.5" /></button> : null}</div>) : <p className="rounded-xl bg-[#f6fafc] p-4 text-sm leading-6 text-slate-600">Создайте первое приглашение, чтобы подключить ученика к предмету «Математика».</p>}</div></div></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><ClipboardPlus className="h-5 w-5 text-[#b88318]" /><h2 className="text-lg font-extrabold text-slate-950">Новое домашнее задание</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">Выберите подключённого ученика и несколько заданий из банка ОГЭ.</p><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><Label htmlFor="homework-title">Название</Label><Input id="homework-title" value={title} onChange={event => setTitle(event.target.value)} className="mt-2" /></div><div><Label htmlFor="homework-student">Ученик</Label><select id="homework-student" value={studentId ?? ""} onChange={event => setStudentId(event.target.value ? Number(event.target.value) : null)} className="mt-2 flex h-10 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="">Выберите ученика</option>{activeStudents.map(student => <option key={student.studentId} value={student.studentId}>{student.studentName || student.studentEmail}</option>)}</select></div><div><Label htmlFor="homework-deadline">Срок сдачи</Label><Input id="homework-deadline" type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} className="mt-2" /></div></div>
          <div className="mt-5"><div className="flex items-center justify-between"><Label>Задания</Label><span className="text-xs font-bold text-slate-500">Выбрано: {selectedTasks.length}</span></div><div className="mt-2 max-h-[360px] space-y-2 overflow-y-auto rounded-xl bg-[#f6f8fa] p-3">{catalog.data?.map(task => <label key={task.id} className="flex cursor-pointer items-start gap-3 rounded-lg bg-white p-3 text-sm shadow-sm"><input type="checkbox" checked={selectedTasks.includes(task.id)} onChange={() => toggleTask(task.id)} className="mt-0.5 h-4 w-4 accent-[#0d2945]" /><span><span className="font-extrabold text-slate-900">{task.title}</span><span className="mt-1 block text-xs leading-5 text-slate-500">КИМ {task.kimNumber} · {task.topicTitle}</span></span></label>)}</div></div>
          <Button onClick={() => { if (!studentId) return toast.error("Выберите ученика"); if (!selectedTasks.length) return toast.error("Выберите хотя бы одно задание"); createHomework.mutate({ studentUserId: studentId, title, taskIds: selectedTasks, dueAt: dueDate ? new Date(`${dueDate}T23:59:00`).getTime() : undefined }); }} disabled={createHomework.isPending} className="mt-5 w-full rounded-lg bg-[#0d2945] font-extrabold">Назначить домашнюю работу</Button>
          <div className="mt-8 border-t border-slate-100 pt-5"><div className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-[#2c668f]" /><h3 className="font-extrabold text-slate-900">Последние назначения</h3></div><div className="mt-3 space-y-2">{homework.data?.length ? homework.data.slice(0, 4).map(item => <div key={item.id} className="flex justify-between gap-3 rounded-lg bg-[#f7f9fa] p-3 text-sm"><span><span className="block font-bold text-slate-800">{item.title}</span><span className="text-xs text-slate-500">{item.studentName || "Ученик"}{item.dueAt ? ` · до ${new Date(item.dueAt).toLocaleDateString("ru-RU")}` : " · без срока"}</span></span><Check className="h-4 w-4 text-emerald-600" /></div>) : <p className="text-sm text-slate-500">Назначений пока нет.</p>}</div></div>
        </section></div></main></div>
  );
}
