import { PlatformHeader } from "@/components/PlatformHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Loader2, RefreshCw, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useRoute } from "wouter";

export function Variants() {
  const variants = trpc.publicBank.listVariants.useQuery(); const [entropy, setEntropy] = useState("");
  const session = trpc.publicBank.generateSessionVariant.useQuery({ entropy: entropy || "new-session" }, { enabled: !!entropy });
  return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-10 sm:py-14"><section className="theme-surface rounded-[28px] border p-7 sm:p-10"><Badge className="border-0 bg-[#ff5b14]/14 text-[#ff8b4b] hover:bg-[#ff5b14]/14">ОГЭ · математика</Badge><h1 className="mt-5 text-4xl font-bold tracking-[-.055em] sm:text-6xl">Варианты</h1><p className="theme-muted mt-4 max-w-2xl leading-7">Выберите готовый опубликованный вариант или соберите одноразовую тренировочную последовательность. Вторая опция не сохраняет попытки и не меняет личный прогресс.</p><Button onClick={() => setEntropy(`${Date.now()}-${Math.random()}`)} className="mt-6 bg-[#ff5b14] text-[#101014] hover:bg-[#ff7a35]"><RefreshCw className="mr-2 h-4 w-4" />Собрать свой вариант</Button></section><section className="mt-7 grid gap-5 lg:grid-cols-2"><div className="theme-surface rounded-2xl border p-5"><h2 className="text-xl font-bold">Готовые варианты</h2><div className="mt-4 space-y-3">{variants.isLoading ? <Loader2 className="h-6 w-6 animate-spin text-[#ff5b14]" /> : variants.data?.map(item => <Link key={item.slug} href={`/variants/${item.slug}`}><article className="rounded-xl border border-white/8 bg-white/3 p-4 transition hover:border-[#ff5b14]/45"><p className="font-bold">{item.title}</p><p className="theme-muted mt-1 text-xs">Выпуск: {item.monthKey}</p><span className="mt-3 inline-flex items-center text-sm font-bold text-[#ff8b4b]">Решать вариант <ArrowRight className="ml-2 h-4 w-4" /></span></article></Link>)}</div></div><div className="theme-surface rounded-2xl border p-5"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-[#ff7a35]" /><h2 className="text-xl font-bold">Свой вариант</h2></div><p className="theme-muted mt-2 text-sm">25 позиций в экзаменационном порядке: №1–19 и №20–25.</p><div className="mt-4 space-y-2">{session.data?.map(item => <div key={`${entropy}-${item.id}`} className="rounded-lg border border-white/8 bg-white/3 p-3 text-sm"><span className="mr-2 font-bold text-[#ff8b4b]">№ {item.sortOrder}</span>{item.title}</div>)}</div>{entropy && session.data ? <Link href={`/variants/session/${encodeURIComponent(entropy)}/solve`}><Button className="mt-5 bg-[#ff5b14] text-[#101014] hover:bg-[#ff7a35]">Решать свой вариант</Button></Link> : null}</div></section></main></div>;
}

export function VariantDetail() {
  const [, params] = useRoute("/variants/:slug"); const data = trpc.publicBank.getVariant.useQuery({ slug: params?.slug ?? "" }, { enabled: !!params?.slug });
  return <div className="theme-page min-h-screen"><PlatformHeader /><main className="container py-10 sm:py-14">{data.isLoading ? <Loader2 className="h-7 w-7 animate-spin text-[#ff5b14]" /> : data.data ? <><section className="theme-surface rounded-[28px] border p-7"><Badge className="border-0 bg-[#ff5b14]/14 text-[#ff8b4b]">Опубликованный вариант</Badge><h1 className="mt-4 text-4xl font-bold">{data.data.title}</h1><p className="theme-muted mt-3">Откройте непрерывный режим решения или выберите отдельную позицию.</p><Link href={`/variants/${data.data.slug}/solve`}><Button className="mt-5 bg-[#ff5b14] text-[#101014]">Решать весь вариант</Button></Link></section><section className="mt-6 grid gap-3 sm:grid-cols-2">{data.data.items.map(item => <Link key={item.taskId} href={`/variants/${data.data.slug}/solve`}><article className="theme-surface rounded-xl border p-4 transition hover:border-[#ff5b14]/45"><p className="text-xs font-bold text-[#ff8b4b]">Позиция {item.sortOrder} · КИМ № {item.kimNumber}</p><h2 className="mt-2 font-bold">{item.title}</h2><p className="theme-muted mt-2 line-clamp-2 text-sm">{item.statementMarkdown}</p></article></Link>)}</section></> : <p className="theme-muted">Вариант не найден.</p>}</main></div>;
}
