/**
 * Object storage with two interchangeable backends.
 *
 * - **local** — a directory on disk. Default, needs no accounts, and on Railway
 *   it becomes a mounted volume by pointing `STORAGE_DIR` at the mount path.
 * - **s3** — any S3-compatible service (Cloudflare R2, Yandex Object Storage,
 *   Selectel, Backblaze B2, MinIO). Selected automatically once the `S3_*`
 *   variables are set.
 *
 * Callers only ever see `/media/<key>`, never a bucket URL, so the backend can
 * change without rewriting rows in `task_visuals`. `registerStorageProxy`
 * resolves that path at request time.
 */

import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import {
  DeleteObjectCommand,
  GetObjectCommand,
  PutObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { ENV } from "./_core/env";

/** Public path prefix served by `registerStorageProxy`. */
export const MEDIA_PREFIX = "/media";

export type StorageBackend = "local" | "s3";

export function storageBackend(): StorageBackend {
  return ENV.s3Bucket && ENV.s3AccessKeyId && ENV.s3SecretAccessKey && ENV.s3Endpoint
    ? "s3"
    : "local";
}

/** Storage always works: without S3 credentials it falls back to local disk. */
export function isStorageConfigured(): boolean {
  return true;
}

// --- shared helpers --------------------------------------------------------

/**
 * Reject anything that could escape the storage root once joined to a path.
 * Keys are opaque and generated by us, so this only ever fires on tampering.
 */
function normalizeKey(relKey: string): string {
  const trimmed = relKey.replace(/^\/+/, "");
  if (
    !trimmed ||
    trimmed.includes("..") ||
    trimmed.includes("\0") ||
    path.isAbsolute(trimmed) ||
    /^[a-zA-Z]:/.test(trimmed)
  ) {
    throw new Error(`Invalid storage key: ${relKey}`);
  }
  return trimmed;
}

/** Keep uploads with the same filename from overwriting each other. */
function appendHashSuffix(relKey: string): string {
  const hash = crypto.randomUUID().replace(/-/g, "").slice(0, 8);
  const lastDot = relKey.lastIndexOf(".");
  if (lastDot === -1) return `${relKey}_${hash}`;
  return `${relKey.slice(0, lastDot)}_${hash}${relKey.slice(lastDot)}`;
}

// --- local backend ---------------------------------------------------------

function storageRoot(): string {
  return path.resolve(ENV.storageDir || "storage");
}

/** Absolute path for a key, verified to stay inside the storage root. */
export function localPathFor(relKey: string): string {
  const root = storageRoot();
  const resolved = path.resolve(root, normalizeKey(relKey));
  // Second line of defence: even if normalizeKey ever missed something, a path
  // outside the root must never be read or written.
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw new Error(`Invalid storage key: ${relKey}`);
  }
  return resolved;
}

// --- s3 backend ------------------------------------------------------------

let client: S3Client | null = null;

function getClient(): S3Client {
  if (!client) {
    client = new S3Client({
      region: ENV.s3Region || "auto",
      endpoint: ENV.s3Endpoint,
      credentials: {
        accessKeyId: ENV.s3AccessKeyId,
        secretAccessKey: ENV.s3SecretAccessKey,
      },
      // R2 and most S3 clones require path-style addressing.
      forcePathStyle: true,
    });
  }
  return client;
}

// --- public API ------------------------------------------------------------

export async function storagePut(
  relKey: string,
  data: Buffer | Uint8Array | string,
  contentType = "application/octet-stream",
): Promise<{ key: string; url: string }> {
  const key = appendHashSuffix(normalizeKey(relKey));
  const body = typeof data === "string" ? Buffer.from(data, "utf-8") : Buffer.from(data);

  if (storageBackend() === "s3") {
    await getClient().send(
      new PutObjectCommand({
        Bucket: ENV.s3Bucket,
        Key: key,
        Body: body,
        ContentType: contentType,
      }),
    );
  } else {
    const destination = localPathFor(key);
    await fs.mkdir(path.dirname(destination), { recursive: true });
    await fs.writeFile(destination, body);
  }

  return { key, url: `${MEDIA_PREFIX}/${key}` };
}

export async function storageGet(relKey: string): Promise<{ key: string; url: string }> {
  const key = normalizeKey(relKey);
  return { key, url: `${MEDIA_PREFIX}/${key}` };
}

/** Time-limited direct URL. S3 only — local files are streamed by the proxy. */
export async function storageGetSignedUrl(
  relKey: string,
  expiresInSeconds = 3600,
): Promise<string> {
  if (storageBackend() !== "s3") {
    throw new Error("Signed URLs require an S3 backend");
  }
  const key = normalizeKey(relKey);
  return getSignedUrl(
    getClient(),
    new GetObjectCommand({ Bucket: ENV.s3Bucket, Key: key }),
    { expiresIn: expiresInSeconds },
  );
}

export async function storageDelete(relKey: string): Promise<void> {
  const key = normalizeKey(relKey);
  if (storageBackend() === "s3") {
    await getClient().send(new DeleteObjectCommand({ Bucket: ENV.s3Bucket, Key: key }));
    return;
  }
  await fs.rm(localPathFor(key), { force: true });
}

/** Public URL when the bucket is served by a CDN, otherwise null. */
export function storagePublicUrl(relKey: string): string | null {
  if (storageBackend() !== "s3" || !ENV.s3PublicUrl) return null;
  return `${ENV.s3PublicUrl.replace(/\/+$/, "")}/${normalizeKey(relKey)}`;
}
